### ISSUE TITLE
$string doesn't output to JSON string

### ISSUE THREAD

**Issue by chery1nguyen** [dashjoin/jsonata-java#15]
Input:
{"example": [{"value":4},{"value":7},{"value":13}]}

Expression:
$string(example)

In JSonata Exerciser, it outputs as:
"[{\"value\":4},{\"value\":7},{\"value\":13}]"

When I tested this locally, it outputs as:
[{"value":4},{"value":7},{"value":13}]

I have a use case where I need to map a field to a json string (escape with \).

**Comment by uw4** [comment]
First I was also confused, but it works correctly:
the result of Jsonata.evaluate is a String (in the original lib it's a Javascript String).
This is covered in test case 
https://github.com/jsonata-js/jsonata/blob/master/test/test-suite/groups/function-string/case016.json
(and others) so it works correctly. It's a bit confusing that in the test case it's also defined as JSON :-)

The Jsonata exerciser additionally does a JSON.stringify to show it
https://github.com/jsonata-js/jsonata-exerciser/blob/d17f0f67522bb741be62fad8fc8ab8089f2a57ed/src/Exerciser.js#L400C49-L400C49

If you want the same in Java, you can use i.e. Jackson writeValueAsString
```java
String data = "{\"example\": [{\"value\":  4},{\"value\":7},{\"value\":13}]}";

Jsonata jsonata = new Jsonata("$string(example)");
Object result = jsonata.evaluate(Json.parseJson(data));

System.out.println("Result=" + result + " type=" + result.getClass());
System.out.println("valueAsString=" + new ObjectMapper().writeValueAsString(result));
```

Output:
```
Result=[{"value":4},{"value":7},{"value":13}] type=class java.lang.String
valueAsString="[{\"value\":4},{\"value\":7},{\"value\":13}]"
```

**Comment by aeberhart** [comment]
It would be nice to add the equivalent of new ObjectMapper().writeValueAsString(result) in the Json parser

**Comment by aeberhart** [comment]
It actually is already available via Function.string()
https://github.com/dashjoin/jsonata-java/blob/main/samples/json-interop.md#built-in-json-parsing-and-stringifying
