### ISSUE TITLE
Possibility to bind lambda without parameters

### ISSUE THREAD

**Issue by leranezabudka** [dashjoin/jsonata-java#17]
I would like to bind lambda without parameters in order to use function instead of variable (to pass random() instead of random to jsonata). This is what I'm trying to do:
val expression = jsonata("${'$'}random()")
val env = expression.createFrame()
env.bind("random") { Random.nextInt(0, 100) }
expression.evaluate(data, env)

I always get the following exception: Attempted to invoke a non-function {code=T1006 position=0}. Can you please answer my question: is it possible to pass function() without parameters to jsonata? Or I should use variable like in your example in case when there are no arguments? (env.bind("PI", Math.PI);)

**Comment by aeberhart** [comment]
I ran into the same issue. Check out the workaround here: #18

**Comment by leranezabudka** [comment]
Thank you very much for the answer!
