### ISSUE TITLE
Is Jsonata#evaluate thread safe?

### ISSUE THREAD

**Issue by Zane-XY** [dashjoin/jsonata-java#24]
I saw after calling the `evaluate` method, the `Jsonata` object state has changed. It seems this evaluate method is not thread safe. Given that if a expression is a constant, and using this constant expression to transform different inputs, is there a way to reuse the created `Jsonata` expression instance?

**Comment by aeberhart** [comment]
Thanks for raising this. We need to provide documentation.
This test case (https://github.com/dashjoin/jsonata-java/blob/main/src/test/java/com/dashjoin/jsonata/ThreadTest.java) shows that a parsed expression can be reused.

We're investigating some cases where there might be issues (e.g. #25)
