### ISSUE TITLE
Bug in $split function when using "." as a seperator

### ISSUE THREAD

**Issue by ayk16** [dashjoin/jsonata-java#29]
This JSONata Expression is giving empty array as output
$split("so.many.words", ".")
where as JSONata Exerciser gives a different output - https://try.jsonata.org/WzYbGpPzc
it works for other characters like " " ,
Infact this is also giving the correct output $split("so.many.words", "\[.]\")
Only the one I shared at the top is not working as expected

**Comment by uw4** [comment]
Root cause:  $split's string separator is wrongly treated as regexp.
So any string that contains regexp syntax produces wrong results
