### ISSUE TITLE
$each function throws NullPointer exception when input is null

### ISSUE THREAD

**Issue by ayk16** [dashjoin/jsonata-java#30]
This JSONata expression is working fine in JSONata Exerciser -
`{ 
    "severity":
    $exists(
        $severity:=$filter(
            $each(
                $sift(
                    attributes
                    ,function($v, $k){$contains($k,/.*level$/) and $uppercase($v) in ["ALL", "TRACE", "DEBUG", "INFO", "WARN", "ERROR", "FATAL", "OFF"]}
                )
                , function($v, $k){$uppercase($v)}
            )
            , function($v, $i){$i = 0}
        )
    )
    ?
        $severity
        :"UNKNOWN"
}`
Here is JSONata Exerciser link with input - https://try.jsonata.org/QSgpuVagm
But the library is throwing NullPointerException
The reason that there is a bug in $each function,
for the given input
output of $sift is null
when $each receives null as input, it throws the exception.

**Comment by uw4** [comment]
Refactored the expression to debug step by step - maybe it's useful:

```
(
    $LEVELS := ["ALL", "TRACE", "DEBUG", "INFO", "WARN", "ERROR", "FATAL", "OFF"];
    $kv := $sift(attributes, function($v, $k) { $contains($k, /.*level$/) } );
    $level:= $each($kv, $uppercase)[0];
    $severity := $level in $LEVELS ? $level : "UNKNOWN";

    {  "severity": $severity }
)
```

https://try.jsonata.org/oL90QIlhs
