### ISSUE TITLE
Make JSONata classes serializable

### ISSUE THREAD

**Issue by uw4** [dashjoin/jsonata-java#33]
Use case:
make (parsed) JSONata expressions usable with RMI, Apache Ignite, Hazelcast etc.

**Comment by aeberhart** [comment]
Unfortunately this is not that simple. If I understand this issue correctly, we would like a parsed expression to be serializable such that it can be passed around a cluster. This means that this test code needs to pass:

```
    Jsonata expr = jsonata("1+2");
    ObjectOutputStream os = new ObjectOutputStream(new ByteArrayOutputStream());
    os.writeObject(expr);
```

expr ultimately includes all the jsonata bindings for $sum, $split, etc. which are JFunctions. Those, in turn, reference the java.lang.reflect.Method which is not serializable.

**Comment by uw4** [comment]
Apart from the Method issue, a quick test showed that:

1) even simple parsed expressions yield "large" serializations:
around 18 kB

2) contain unnecessary (recomputable) data which should be treated private (internal representation might change in future versions of the lib) and should be transient:
- parser's symbol table
- default functions (staticFrame)
- all unserializable bindings (like methods)

3) without the unnecessary data:
parsed expressions are serialized to 2 kB (factor 9-10x smaller)
